apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: greetings.k8s.rael.io
spec:
  group: k8s.rael.io
  names:
    kind: Greeting
    listKind: GreetingList
    plural: greetings
    singular: greeting
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
